### ISSUE TITLE
Order of the tabs should be Wine Notes | Wine Story | Accolades & Awards 

### ISSUE THREAD

**Issue by Valenie** [ajency/Wine-subscription#93] opened 2017-05-26 10:01 UTC
![image](https://cloud.githubusercontent.com/assets/19943710/26490279/4a170bc2-4228-11e7-9597-f07a64eaf92b.png)

**Comment by ajajrajguru** [comment] 2017-05-26 12:12
Duplicate of #94

**Closed as completed** 2017-05-29 05:37 UTC
Labels: Assigned to QA
